Symfony 4 Compatibility
propelorm/PropelBundle pull request #476
Opened 2017-11-18 14:09 UTC by macroprog

2018-01-10 13:00 UTC, cristianoc72 commented
Please, could you re-run travis? After merging https://github.com/propelorm/Propel2/pull/1434 test suite should be green.
Thank you!

2018-01-10 14:07 UTC, gharlan requested changes

2018-01-10 14:07 UTC, gharlan commented on Resources/config/propel.xml
> +            <argument type="service" id="faker.generator" on-invalid="null" public="true"/>
I guess the `public="true"` is wrong here (`argument`s don't have a `public` attribute).

2018-01-27 22:19 UTC, macroprog commented
My last commit is green, I left you see if it's usefull to merge it to the master...

2018-01-28 15:48 UTC, cristianoc72 commented
Thank you to include my branch 4.0 into your PR!
Anyway, I'm asking you (and the PropelBundle team) to consider the following points:
1. I refactored the bundle to be Symfony 4.0 only, so it's better to create a new `4.0` branch in Propel repository, instead of merging it into 3.0, because it beaks compatibility with Symfony 3.
2. My 4.0 branch is not finished yet: I have to test the commands behavior with the new directory structure. I plan to do this in a couple of days.
3. Since Symfony 4 directory structure is different from previous versions, there are some changes in PropelBundle 4.0 branch that should be documented. I plan to write a new recipe for Propel cookbook at the end of the next week.
4. Last but not the least, I'm working on a Symfony flex recipe for PropelBundle, so that we could install PropelBundle and Propel simply with `composer require propel`. 

Please, have a little patience again 😄

2018-02-02 18:43 UTC, kingchills commented
I too have been working on a [4.0 branch](https://github.com/kingchills/PropelBundle/tree/4.0) for this.  Please feel free to use any of my work on this.  I have implemented registering of the commands, and have tested most of them.  My unit tests all come back green.  One of my concerns of your current work is setting all of the services to be public, which isn't considered best practices within symfony.  Also your changes in Command/AbstractCommand.php are unnecessary if files are placed in the proper place (schemas will be found and moved to the cache if placed in src/propel/*schema.xml).

2018-02-02 18:45 UTC, kingchills commented on composer.json
> +        "symfony/security-acl": "For using acl instead of voters"
Does this need to be in the "suggest" if it is in the require?

2018-02-02 18:49 UTC, kingchills commented on composer.json
> +        "symfony/security-acl": "^3.0",
Does not need to be in "require-dev" when in require

2018-02-05 08:30 UTC, cristianoc72 commented
@kingchills your work is almost perfect, and it's compatible with Symfony 3.4, too! Why don't you submit a PR? Imho, your 4.0 branch is already mergeable, as is.

2018-02-05 14:19 UTC, kingchills commented
@cristianoc72  Consider it done.

2022-11-21 11:49 UTC, dereuromark commented
Shall we continue here?

2022-11-21 11:52 UTC, ilohpro commented
It's quite old, I think this pull request has to been fully reviewed on new versions.
Personnally, i don't use it anymore, maybe i should close this PR too.

2022-11-21 11:58 UTC, dereuromark commented
Actually, https://github.com/SkyFoxvn/PropelBundle will most likely be the follower of this now.

2022-11-21 11:58 UTC, closed without merging